# agents/orchestrator.py
from graph.state import FinSightState

def orchestrator_node(state: FinSightState) -> dict:
    """
    Prepares state before routing to agents.
    In week 2, this will call your RAG retriever.
    For now, returns placeholder docs.
    """
    # TODO week 2: replace with real RAG retrieval
    # from tools.retriever import retrieve
    # docs = retrieve(state["company"], state["user_query"])

    placeholder_docs = [
        f"{state['company']} Q3 earnings showed 12% revenue growth YoY.",
        f"{state['company']} faces regulatory headwinds in EU market.",
        f"Analyst consensus for {state['company']}: 8 buy, 3 hold, 1 sell.",
        f"Recent news: {state['company']} announced new product line.",
        f"{state['company']} debt-to-equity ratio improved to 0.45.",
        f"Market volatility index for {state['company']} sector at 18.2.",
    ]

    return {"retrieved_docs": placeholder_docs}


def report_generator_node(state: FinSightState) -> dict:
    """Merges all agent outputs into a structured decision report."""
    risk_emoji = "🔴" if state["risk_score"] > 0.7 else "🟡" if state["risk_score"] > 0.4 else "🟢"
    forecast_emoji = {"buy": "↑", "hold": "→", "sell": "↓"}.get(state["forecast"], "→")

    report = f"""
# FinSight AI — Decision Report
**Company:** {state['company']}
**Query:** {state['user_query']}

---

## Risk Assessment {risk_emoji}
**Score:** {state['risk_score']:.2f} / 1.00
{state['risk_summary']}

## Market Sentiment
**Signal:** {state['sentiment'].upper()} (confidence: {state['sentiment_confidence']:.0%})

## Forecast {forecast_emoji}
**Recommendation:** {state['forecast'].upper()}
{state['forecast_rationale']}

---
*Generated by FinSight AI — RAG + Multi-Agent System*
""".strip()

    return {"decision_report": report}