"""
Report Generator Node — final node in the pipeline.
Merges all agent outputs into a structured decision report.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from langchain_openai import ChatOpenAI

from backend.agents.graph.state import FinSightState
from backend.core.config import settings

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are the Chief Investment Officer of FinSight AI.
Your task is to synthesize the risk analysis, sentiment data, and 30-day forecast into a 
comprehensive, executive-quality financial decision report.

Write a professional investment report with these sections:
1. EXECUTIVE SUMMARY (2-3 sentences)
2. RISK ASSESSMENT (reference the risk score and key risk factors)
3. MARKET SENTIMENT (reference bullish/bearish/neutral with confidence)
4. 30-DAY FORECAST (reference buy/hold/sell recommendation and rationale)
5. FINAL RECOMMENDATION (clear, actionable advice)

The report should be professional, data-driven, and formatted with markdown headers.
Do NOT use bullet points for the main narrative — use flowing paragraphs.
End with a disclaimer about investment risk."""


async def report_generator_node(state: FinSightState) -> FinSightState:
    """
    Synthesize all agent outputs into decision_report.
    This is the final node before END.
    """
    llm = ChatOpenAI(
        model=settings.OPENAI_MODEL,
        temperature=0.1,
        api_key=settings.OPENAI_API_KEY,
    )

    # Format risk level label
    risk_score = state.get("risk_score") or 0.5
    if risk_score > 0.7:
        risk_level = "HIGH"
    elif risk_score > 0.4:
        risk_level = "MEDIUM"
    else:
        risk_level = "LOW"

    user_message = f"""Generate a comprehensive investment decision report for:

Company: {state['company']}
Client Question: {state['user_query']}
Report Date: {datetime.now(timezone.utc).strftime('%B %d, %Y')}

RISK ANALYSIS:
- Risk Score: {risk_score:.2f}/1.00 ({risk_level} RISK)
- Risk Summary: {state.get('risk_summary', 'N/A')}

MARKET SENTIMENT:
- Sentiment: {(state.get('sentiment') or 'neutral').upper()}
- Confidence: {(state.get('sentiment_confidence') or 0.0):.0%}

30-DAY FORECAST:
- Recommendation: {(state.get('forecast') or 'hold').upper()}
- Rationale: {state.get('forecast_rationale', 'N/A')}

Write the full investment report now."""

    try:
        response = await llm.ainvoke([
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ])

        decision_report = response.content.strip()
        logger.info(f"[ReportGenerator] Report generated for {state['company']} ({len(decision_report)} chars)")

        return {**state, "decision_report": decision_report}

    except Exception as exc:
        logger.error(f"[ReportGenerator] Failed: {exc}", exc_info=True)

        # Fallback to structured summary from agent outputs
        fallback_report = _build_fallback_report(state)
        return {**state, "decision_report": fallback_report, "error": str(exc)}


def _build_fallback_report(state: FinSightState) -> str:
    """Build a minimal report if LLM call fails."""
    risk_score = state.get("risk_score") or 0.5
    sentiment = state.get("sentiment") or "neutral"
    forecast = state.get("forecast") or "hold"

    return f"""# FinSight AI Investment Report

## {state['company']} — Investment Analysis

**Executive Summary**
Based on available data, {state['company']} shows a risk score of {risk_score:.2f}/1.00 
with {sentiment} market sentiment. Our recommendation is to **{forecast.upper()}**.

**Risk Assessment**
{state.get('risk_summary', 'Risk data unavailable.')}

**Market Sentiment**
{sentiment.capitalize()} sentiment with {(state.get('sentiment_confidence') or 0.0):.0%} confidence.

**Forecast**
{state.get('forecast_rationale', 'Forecast rationale unavailable.')}

---
*This report is generated by FinSight AI and is for informational purposes only. 
Not financial advice. Past performance does not guarantee future results.*"""
